trigger:
  branches:
    include:
      - staging

pr: none

pool:
  vmImage: "windows-2019"
steps:
  - task: UseNode@1
    inputs:
      checkLatest: true
    displayName: "install latest node"

  - script: |
      yarn
    displayName: "yarn install"
  - script: |
      yarn build
    displayName: "yarn build"

  - task: AzureFileCopy@4
    inputs:
      SourcePath: "build/*"
      azureSubscription: "AzureDevopsServicePrincipal"
      Destination: "AzureBlob"
      storage: "gwengineeringsite "
      ContainerName: "$web"
    displayName: Azure copy build to blob storage
