module.exports = {
    someSidebar: {
        Documents:
            [
"1-introduction",
{
"2-glasswall_core":
    [
    {
    "2_1-glasswall_rebuild":
        [
        "2-glasswall_core/2_1-glasswall_rebuild/2_1_1-product_description",
        {
        "2_1_2-architecture":
            [
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_2-architecture/2_1_2_1-overview",
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_2-architecture/2_1_2_2-auto_generated_cameras",
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_2-architecture/2_1_2_3-legacy_cameras",
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_2-architecture/2_1_2_4-analysis_repository",
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_2-architecture/2_1_2_5-memory_buffers",
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_2-architecture/2_1_2_6-configuration_management"
            ]
        },
        "2-glasswall_core/2_1-glasswall_rebuild/2_1_3-licencing",
        "2-glasswall_core/2_1-glasswall_rebuild/2_1_4-dependencies",
        {
        "2_1_5-build":
            [
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_5-build/2_1_5_1-building_project",
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_5-build/2_1_5_2-versioning"
            ]
        },
        {
        "2_1_6-sdk":
            [
            "2-glasswall_core/2_1-glasswall_rebuild/2_1_6-sdk/2_1_6_1-api",
            {
            "2_1_6_2_sdk_wrappers":
                [
                "2-glasswall_core/2_1-glasswall_rebuild/2_1_6-sdk/2_1_6_2-sdk_wrappers/2_1_6_2_1-python",
                "2-glasswall_core/2_1-glasswall_rebuild/2_1_6-sdk/2_1_6_2-sdk_wrappers/2_1_6_2_2-javascript",
                "2-glasswall_core/2_1-glasswall_rebuild/2_1_6-sdk/2_1_6_2-sdk_wrappers/2_1_6_2_3-c_sharp",
                "2-glasswall_core/2_1-glasswall_rebuild/2_1_6-sdk/2_1_6_2-sdk_wrappers/2_1_6_2_4-java"
                ]
            }
            ]
        },
        "2-glasswall_core/2_1-glasswall_rebuild/2_1_7-rebuild_cli"
        ]
    },
    {
    "2_2-glasswall_editor":
        [
        "2-glasswall_core/2_2-glasswall_editor/2_2_1-product_description",
        {
        "2-glasswall_core/2_2-glasswall_editor/2_2_2-architecture":
            [
            "2-glasswall_core/2_2-glasswall_editor/2_2_2-architecture/2_2_2_1-overview",
            "2-glasswall_core/2_2-glasswall_editor/2_2_2-architecture/2_2_2_2-auto_generated_cameras",
            "2-glasswall_core/2_2-glasswall_editor/2_2_2-architecture/2_2_2_3-analysis_repository",
            "2-glasswall_core/2_2-glasswall_editor/2_2_2-architecture/2_2_2_4-memory_buffers",
            "2-glasswall_core/2_2-glasswall_editor/2_2_2-architecture/2_2_2_5-configuration_management"
            ]
        },
        "2-glasswall_core/2_2-glasswall_editor/2_2_3-licencing",
        "2-glasswall_core/2_2-glasswall_editor/2_2_4-dependencies",
        {
        "2_2_5-build":
            [
            "2-glasswall_core/2_2-glasswall_editor/2_2_5-build/2_2_5_1-building_project",
            "2-glasswall_core/2_2-glasswall_editor/2_2_5-build/2_2_5_2-versioning",
            ]
        },
        {
        "2_2_6-sdk":
            [
            "2-glasswall_core/2_2-glasswall_editor/2_2_6-sdk/2_2_6_1-api",
            {
            "2_2_6_2-sdk_wrappers":
                [
                "2-glasswall_core/2_2-glasswall_editor/2_2_6-sdk/2_2_6_2-sdk_wrappers/2_2_6_2_1-python",
                "2-glasswall_core/2_2-glasswall_editor/2_2_6-sdk/2_2_6_2-sdk_wrappers/2_2_6_2_2-javascript",
                "2-glasswall_core/2_2-glasswall_editor/2_2_6-sdk/2_2_6_2-sdk_wrappers/2_2_6_2_3-c_sharp",
                "2-glasswall_core/2_2-glasswall_editor/2_2_6-sdk/2_2_6_2-sdk_wrappers/2_2_6_2_4-java"
                ]
            }
            ]
        },
        "2-glasswall_core/2_2-glasswall_editor/2_2_7-editor_cli"
        ]
    },
    {
    "2_3-glasswall_word_search":
        [
        "2-glasswall_core/2_3-glasswall_word_search/2_3_1-product_description",
        {
        "2_3_2-architecture":
            [
            "2-glasswall_core/2_3-glasswall_word_search/2_3_2-architecture/2_3_2_1-overview",
            "2-glasswall_core/2_3-glasswall_word_search/2_3_2-architecture/2_3_2_2-configuration_management"
            ]
        },
        "2-glasswall_core/2_3-glasswall_word_search/2_3_3-licencing",
        "2-glasswall_core/2_3-glasswall_word_search/2_3_4-dependencies",
        {
        "2_3_5-build":
            [
            "2-glasswall_core/2_3-glasswall_word_search/2_3_5-build/2_3_5_1-building_project",
            "2-glasswall_core/2_3-glasswall_word_search/2_3_5-build/2_3_5_2-versioning"
            ]
        },
        {
        "2_3_6-sdk":
            [
            "2-glasswall_core/2_3-glasswall_word_search/2_3_6-sdk/2_3_6_1-api",
            {
            "2_3_6_2-sdk_wrappers":
                [
                "2-glasswall_core/2_3-glasswall_word_search/2_3_6-sdk/2_3_6_2-sdk_wrappers/2_3_6_2_1-python",
                "2-glasswall_core/2_3-glasswall_word_search/2_3_6-sdk/2_3_6_2-sdk_wrappers/2_3_6_2_2-javascript",
                "2-glasswall_core/2_3-glasswall_word_search/2_3_6-sdk/2_3_6_2-sdk_wrappers/2_3_6_2_3-c_sharp",
                "2-glasswall_core/2_3-glasswall_word_search/2_3_6-sdk/2_3_6_2-sdk_wrappers/2_3_6_2_4-java"
                ]
            }
            ]
        }
        ]
    },
    {
    "2_4-glasswall_archive_manager":
        [
        "2-glasswall_core/2_4-glasswall_archive_manager/2_4_1-product_description",
        {
        "2_4_2-architecture":
            [
            "2-glasswall_core/2_4-glasswall_archive_manager/2_4_2-architecture/2_4_2_1-overview",
            "2-glasswall_core/2_4-glasswall_archive_manager/2_4_2-architecture/2_4_2_2-configuration_management"
            ]
        },
        "2-glasswall_core/2_4-glasswall_archive_manager/2_4_3-licencing",
        "2-glasswall_core/2_4-glasswall_archive_manager/2_4_4-dependencies",
        {
        "2_4_5-build":
            [
            "2-glasswall_core/2_4-glasswall_archive_manager/2_4_5-build/2_4_5_1-building_project",
            "2-glasswall_core/2_4-glasswall_archive_manager/2_4_5-build/2_4_5_2-versioning"
            ]
        },
        "2-glasswall_core/2_4-glasswall_archive_manager/2_4_6-sdk_api",
        {
        "2_4_7-sdk_wrappers":
            [
            "2-glasswall_core/2_4-glasswall_archive_manager/2_4_7-sdk_wrappers/2_4_7_1-python",
            "2-glasswall_core/2_4-glasswall_archive_manager/2_4_7-sdk_wrappers/2_4_7_2-javascript",
            "2-glasswall_core/2_4-glasswall_archive_manager/2_4_7-sdk_wrappers/2_4_7_3-c_sharp",
            "2-glasswall_core/2_4-glasswall_archive_manager/2_4_7-sdk_wrappers/2_4_7_4-java",
            ]
        }
        ]
    }
    ]
},
"3-guides",
{
"4-testing":
    [
    "4-testing/4_1-core_test_strategy",
    "4-testing/4_2-automated_testing",
    "4-testing/4_3-manual_testing",
    "4-testing/4_4-testing_guidelines"
    ]
},
{
"5-development":
    [
    "5-development/5_1-development_process",
    "5-development/5_2-coding_guidelines",
    "5-development/5_3-branching_strategy",
    "5-development/5_4-unit_testing"
    ]
},
{
"6-deployment":
    [
    {
    "6_1-release_process":
        [
        "6-deployment/6_1-release_process/6_1_1-overview",
        "6-deployment/6_1-release_process/6_1_2-release_notes"
        ]
    }
    ]
},
"7-tools",
{
"8-related":
    [
    {
    "8_1-specifications":
        [
        {
        "8_1_1-ms_office":
            [
            "8-related/8_1-specifications/8_1_1-ms_office/8_1_1_1-office_open_xml",
            "8-related/8_1-specifications/8_1_1-ms_office/8_1_1_2-office_binary"
            ]
        },
        "8-related/8_1-specifications/8_1_2-pdf",
        "8-related/8_1-specifications/8_1_3-jpeg",
        "8-related/8_1-specifications/8_1_4-png",
        "8-related/8_1-specifications/8_1_5-gif",
        "8-related/8_1-specifications/8_1_6-tiff"
        ]
    }
    ]
}
]
},
};