name: PushFile

on:
  push:
    branches: master
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: create new directory
      run: |
        mkdir -p files-to-copy/archive.manager
        cp "docs/2-glasswall_core/2_2-glasswall_editor/2_2_6-sdk/2_2_6_1-api/2_2_6_1_5-archivemanager/2_2_6_1_5_1-archive-manager.md" "files-to-copy/archive.manager/README.md"
        
        mkdir -p files-to-copy/word.search
        cp "docs/2-glasswall_core/2_2-glasswall_editor/2_2_6-sdk/2_2_6_1-api/2_2_6_1_4-wordsearch/2_2_6_1_4_1-wordsearch.md" "files-to-copy/word.search/README.md"
        
        cd files-to-copy
        ls -R
        
    - name: Pushs Archive manager to rebuid
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.DOCUMENTATION_API_KEY }}
      with:
        source_file: 'files-to-copy/archive.manager/README.md'
        destination_repo: 'filetrust/sdk-rebuild'
        destination_folder: 'libs/extensions/archive.manager'
        user_email: "bkubheka@glasswallsolutions.com"
        user_name: "gwBanzi"
        
    - name: Pushs Archive manager to editor
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.DOCUMENTATION_API_KEY }}
      with:
        source_file: 'files-to-copy/archive.manager/README.md'
        destination_repo: 'filetrust/sdk-editor'
        destination_folder: 'libs/extensions/archive.manager'
        user_email: "bkubheka@glasswallsolutions.com"
        user_name: "gwBanzi"
        
    - name: Push Word Search to Editor
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.DOCUMENTATION_API_KEY }}
      with:
        source_file: 'files-to-copy/word.search/README.md'
        destination_repo: 'filetrust/sdk-editor'
        destination_folder: 'libs/extensions/word.search'
        user_email: "bkubheka@glasswallsolutions.com"
        user_name: "gwBanzi"
